name: DeSmuME

on:
  - push
  - pull_request

jobs:
  build:
    name: Build DeSmuME (Linux/GTK+2)
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt update && sudo apt install autoconf libglu1-mesa-dev libsdl2-dev libpcap-dev libgtk2.0-dev

      - name: buildit
        run: |
          cd desmume/src/frontend/posix/
          autoreconf -i
          ./configure --prefix=/usr --enable-gdb-stub --enable-wifi
          make -j8
          make DESTDIR=/tmp/DeSmuME install

      - name: Pack artifact
        run: |
          cd /tmp
          tar cJf DeSmuME.tar.xz DeSmuME/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: desmume-linux-gtk2-cli-x86_64
          path: /tmp/DeSmuME.tar.xz
